version: 0.0.0
name: chainlinkFeeds
description: Chainlink feeds
repository: https://github.com/Float-Capital/chainlink-feeds
networks:
  - id: 42161
    start_block: 121690634
    contracts:
      - name: ArbFeeds
        address:
          - "0x7AAeE6aD40a947A162DEAb5aFD0A1e12BE6FF871"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  - id: 56
    start_block: 30879439
    contracts:
      - name: BscFeeds
        address:
          - "0xD2528B74ca91Bb07B9bd9685ce533367C6fa657C"
          - "0x6c9C9757F0478bC38Bf73ABdA27ac42864De0645"
          - "0x2f92dc0711AdA3dc255e2197e7c15C8aDC6b6537"
          - "0xE0A34B8FC5e80C877fd568bd22b49E1BCa977B6F"
          - "0x6a6eb03007131EAe9D02f66289a82d784c4EeA50"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  - id: 10
    start_block: 108259548
    contracts:
      - name: OpFeeds
        address:
          - "0xAA75acE4575AbBE1D237D991a7461f497a56a8F0"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  - id: 137
    start_block: 46342962
    contracts:
      - name: PolygonFeeds
        address:
          - "0x0a9823c5cd84099fde8566a1adf0f2bb41cc6e7d"
          - "0x6dbd1be1a83005d26b582d61937b406300b05a8f"
          - "0x88b79bfce730bbb74f23ab8940b37b86859caa2e"
          - "0x4dd6655ad5ed7c06c882f496e3f42ace5766cb89"
          - "0x8123beacb5bca3afa0c9ff71b28549d58cec8176"
          - "0xf07eac7a48eb772613479d6a8fc42675f1befb47"
          - "0x310990e8091b5cf083fa55f500f140cfbb959016"
          - "0x3f7f90e0f782e325401f6323ba93e717f519f382"
          - "0x39e5e33c923bb56a7e2ae644564f94b80630f3e3"
          - "0x2e2ed40fc4f1774def278830f8fe3b6e77956ec8"
          - "0xeaf35f06410014234bee87980a902c21f78cb426"
          - "0xfd54f97a6c408561b5df798c04ae08b27ca0d7f7"
          - "0x8a2355ec4678186164dc17dfc2c5d0d083d7fd66"
          - "0x542d2af7f89a61205f3da2d3d13e29b56bde7b46"
          - "0x704179beb09282eaef98ca8aaa443c1e273ebbc2"
          - "0x45ede0ea5cbbe380c663c7c3015cc7c986669fec"
          - "0x08f8d217e6f07ae423a2ad2ffb226ffcb577708d"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  - id: 43114
    start_block: 33959050
    contracts:
      - name: AvalancheFeeds
        address:
          - "0x95edda00bce60f99fb0be38fe500ebd879ab651a"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"